# Generated by Django 5.2.6 on 2025-10-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bb_additionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='contacts',
            field=models.CharField(max_length=50, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.CharField(max_length=600, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(default=0, max_length=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Товар'),
        ),
    ]
