# Generated by Django 5.2.6 on 2025-10-10 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bb_contacts_alter_bb_content_alter_bb_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='Цена'),
        ),
    ]
