# Generated by Django 5.2.6 on 2025-10-10 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(1000000000)], verbose_name='Цена'),
        ),
    ]
