# Generated by Django 5.2.6 on 2025-10-10 13:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bb_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalimage',
            options={},
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999.99)], verbose_name='Цена'),
        ),
    ]
