# Generated by Django 5.2.6 on 2026-01-13 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999.99)], verbose_name='Цена'),
        ),
    ]
